---
editor_options:
  chunk_output_type: console
---

# Site selection  

The aim of this script is to provide .geojson files to Planet to obtain access to high-resolution satellite data for the Western Ghats

## Load necessary libraries
```{r}
library(sf)
library(tidyverse)
library(mapview)
library(mapedit)
library(purrr)
library(terra)
library(spatstat.random)

# for plotting
library(viridis)
library(colorspace)
library(scales)
library(ggplot2)
library(patchwork)
library(fastmap)
```


## Load the Western Ghats outline and edit it interactively to draw bounding boxes for the Nilgiris and the Anamalais

```{r}
wg <- st_read("data/spatial/WG.shp")
wg <- st_make_valid(wg)

# create bounding box/polygon interactively for the region of interest
# for the sake of this exercise, we created a bounding box that is larger than the total area required for sampling

# Including requests from keystone and ncf for nilgiris and anamalais
str <- st_read("data/spatial/STR_boundaries.shp") 
atr <- st_read("data/spatial/ATR Outer boundary.geojson")

area_for_editing <- mapview(str) + mapview(atr)

bbox <- area_for_editing %>%
 editMap()

# check if overall area is <15,000 sq.km
st_area(bbox$finished)/ 1000000

# create files for exporting
roi <- st_as_sf(bbox$finished) %>%
  `st_crs<-`(4326)

# including shapefiles for central and northern Western Ghats
mapviewOptions(fgb = FALSE)
dodamarg <- st_read("data/spatial/dodamarg.shp") %>%
  st_zm(., drop = TRUE, what = "ZM") %>%
  st_make_valid()
dodamarg$feature_type <- "polygon"

# kadamane 
kadamane <- st_read("data/spatial/kadamane.geojson") %>%
  st_zm(., drop = TRUE, what = "ZM") %>%
  st_make_valid()

# combining the shapefiles (combine specific rows)
combined_shp <- bind_rows(roi[,2:3], dodamarg[,c(12,13)], kadamane[4,c(2,14)]) %>%
  filter(!is.na(geometry))

# check if overall area is <15,000 sq.km (total ~14,460)
sum(st_area(combined_shp)/ 1000000)

# export
st_write(combined_shp, "data/spatial/western_ghats.json",
         driver = "GeoJSON")
```

## Creating an interactive file to view the region of interest

```{r}
# to save this to a file 
# if you would like to share this with collaborators/colleagues

html_fl <- tempfile(tmpdir = getwd(), fileext = "interactive-visualization.html")

view <- mapview(wg, col.regions = "gray") +
  mapview(combined_shp, col.regions = "red")

# create standalone .html
mapview::mapshot(view, url = html_fl)

view
```

<iframe src="interactive-visualization.html" height="600px" width="100%" style="border:none;"></iframe>

